---
- hosts: aws_servers_1
  become: yes
  tasks:
    - name: install docker
      apt:
        name: docker.io
        update_cache: yes
        state: latest
      notify: start docker

  handlers:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes


